name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Restore generated site
        uses: actions/download-artifact@v7
        with:
          name: output_prod
          path: output_prod

      - name: Push build to gh-pages branch
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: output_prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: "github-actions[bot]"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          MESSAGE: "Build of {long-sha} ({msg})"
